config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :categories
  resources :transactions
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :transactions

  validates :name, presence: true # Name of category
  validates :income, inclusion: { in: [true, false, nil] } # Type of income (Income, Expense, Neutral)
  validates :user_id, presence: true # user_id (A category is specific for to a user)
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user
  belongs_to :category

  validates :name, presence: true # Name of transaction
  validates :transaction_date, presence: true # Date of transaction
  validates :price, presence: true # Price of transaction
  validates :category_id, presence: true # Category linked to the transaction
  validates :user_id, presence: true # user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :transactions
  has_many :categories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_user
end

private

def set_user
  # Set user if present
  @user = current_user if current_user.present?
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only: %i[edit update destroy]

  # GET /categories or /categories.json
  def index
    @categories = @user.categories
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit; end

  # POST /categories or /categories.json
  def create
    params[:category][:income] = nil if params[:category][:income] == "neutral"
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_url, notice: 'Category was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      params[:category][:income] = nil if params[:category][:income] == "neutral"
      if @category.update(category_params)
        format.html { redirect_to categories_url, notice: 'Category was successfully updated.' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

    # Only allow a list of trusted parameters through.
  def category_params
    params.fetch(:category, {}).permit(:name, :income, :user_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # Landing page
  def index
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :authenticate_user! # Make sure user is signed in
  before_action :set_transaction, only: %i[edit update destroy]

  # GET /transactions or /transactions.json
  def index
    @transactions = @user.transactions
    @categories = @user.categories
    @year = if params[:year].present?
              params[:year]
            else
              Date.today.year
            end

    respond_to do |format|
      format.js
      format.html
    end
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit; end

  # POST /transactions or /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to transactions_url, notice: 'Transaction was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1 or /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to transactions_url, notice: 'Transaction was successfully updated.' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1 or /transactions/1.json
  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_url, notice: 'Transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_transaction
    @transaction = Transaction.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def transaction_params
    params.fetch(:transaction, {}).permit(:price, :transaction_date, :category_id, :user_id, :name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper

  def month_transactions(month, year)
    # Get all transactions for a particular month (and year), ordered by date of transaction ASC
    date = Date.new(year.to_i, Date::MONTHNAMES.index(month))
    @user.transactions.where('transaction_date >= ? and transaction_date <= ?',
                                                       date.beginning_of_month,
                                                       date.end_of_month).order(transaction_date: :ASC)
  end

  def sum_of_category_for_month(category, month, year)
    # Sum of all month's transactions for a specfic category
    month_transactions(month, year.to_i).where(category: category).sum(:price)
  end

  def total_sum_for_month(month, year, income)
    # Sum of all month's transactions
    date = Date.new(year.to_i, Date::MONTHNAMES.index(month))
    @user.transactions.joins(:category).where(category: { income: income }).where('transaction_date >= ? and transaction_date <= ?',
                             date.beginning_of_month,
                             date.end_of_month).sum(:price)
  end

  def sum_of_category_for_year(category, year)
    # Sum for a specific category for a full year
    date = Date.new(year.to_i)
    @user.transactions.where(category: category).where('transaction_date >= ? and transaction_date <= ?',
                                                       date.beginning_of_year,
                                                       date.end_of_year).sum(:price)
  end

  def total_sum_for_year(year, income)
    # Sum of all transactions for a year
    date = Date.new(year.to_i)
    @user.transactions.joins(:category).where(category: { income: income })
         .where('transaction_date >= ? and transaction_date <= ?',
                             date.beginning_of_year,
                             date.end_of_year).sum(:price)
  end

  def year_select
    # Select year shown
    year = if !@user.transactions.order(transaction_date: :asc).present? || @user.transactions.order(transaction_date: :asc).first.transaction_date.year > Date.today.year
             Date.today.year
           else
             @user.transactions.order(transaction_date: :asc).first.created_at.year
           end
    (year..Date.today.year).to_a
  end
end

app/views/categories/_form.html.erb
<%= form_with(model: category) do |f| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= f.label :name, "Category Name", { class: "form-label"} %>
    <%= f.text_field :name, { class: "form-control", placeholder: "Food", required: true } %>
  </div>

  <div class="form-check">
    <%= f.radio_button :income, true, class: "form-check-input" %>
    <%= f.label :income, "Income", { class: "form-label"} %>
  </div>

  <div class="form-check">
    <%= f.radio_button :income, "neutral", class: "form-check-input" %>
    <%= f.label :income, "Neutral", { class: "form-label"} %>
  </div>

  <div class="form-check">
    <%= f.radio_button :income, false, class: "form-check-input" %>
    <%= f.label :income, "Expenses", { class: "form-label"} %>
  </div>

  <%= f.hidden_field :user_id, value: @user.id, required: true %>

  <div class="actions">
    <%= f.submit "Submit", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Categories</h1>

<%= link_to 'Add Category', new_category_path, class: 'btn btn-outline-primary' %>
<%= link_to 'Go to Transactions', transactions_path, class: 'btn btn-outline-primary' %>

<br><br>

<% if @categories.count > 0 %>
  <table class="table">
    <thead>
    <tr>
      <th scope="col">#</th>
      <th>Name</th>
      <th>Type</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
    </thead>

    <tbody>
    <% @categories.each_with_index do |category, index| %>
      <tr>
        <th scope="row"><%= index %></th>
        <td><%= category.name %></td>
        <td>
          <% if category.income == nil %>
            Neutral
          <% elsif category.income? %>
            Income
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-coin text-success" viewBox="0 0 16 16">
              <path d="M5.5 9.511c.076.954.83 1.697 2.182 1.785V12h.6v-.709c1.4-.098 2.218-.846 2.218-1.932 0-.987-.626-1.496-1.745-1.76l-.473-.112V5.57c.6.068.982.396 1.074.85h1.052c-.076-.919-.864-1.638-2.126-1.716V4h-.6v.719c-1.195.117-2.01.836-2.01 1.853 0 .9.606 1.472 1.613 1.707l.397.098v2.034c-.615-.093-1.022-.43-1.114-.9H5.5zm2.177-2.166c-.59-.137-.91-.416-.91-.836 0-.47.345-.822.915-.925v1.76h-.005zm.692 1.193c.717.166 1.048.435 1.048.91 0 .542-.412.914-1.135.982V8.518l.087.02z"/>
              <path fill-rule="evenodd" d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
              <path fill-rule="evenodd" d="M8 13.5a5.5 5.5 0 1 0 0-11 5.5 5.5 0 0 0 0 11zm0 .5A6 6 0 1 0 8 2a6 6 0 0 0 0 12z"/>
            </svg>
          <% else %>
            Expense
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-coin text-danger" viewBox="0 0 16 16">
              <path d="M5.5 9.511c.076.954.83 1.697 2.182 1.785V12h.6v-.709c1.4-.098 2.218-.846 2.218-1.932 0-.987-.626-1.496-1.745-1.76l-.473-.112V5.57c.6.068.982.396 1.074.85h1.052c-.076-.919-.864-1.638-2.126-1.716V4h-.6v.719c-1.195.117-2.01.836-2.01 1.853 0 .9.606 1.472 1.613 1.707l.397.098v2.034c-.615-.093-1.022-.43-1.114-.9H5.5zm2.177-2.166c-.59-.137-.91-.416-.91-.836 0-.47.345-.822.915-.925v1.76h-.005zm.692 1.193c.717.166 1.048.435 1.048.91 0 .542-.412.914-1.135.982V8.518l.087.02z"/>
              <path fill-rule="evenodd" d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
              <path fill-rule="evenodd" d="M8 13.5a5.5 5.5 0 1 0 0-11 5.5 5.5 0 0 0 0 11zm0 .5A6 6 0 1 0 8 2a6 6 0 0 0 0 12z"/>
            </svg>
          <% end %>
        </td>
        <td><%= link_to 'Edit', edit_category_path(category), class: "btn btn-secondary" %></td>
        <td><%= link_to 'Delete', category, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alert alert-warning d-flex align-items-center" role="alert">
    <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Warning:">
      <use xlink:href="#exclamation-triangle-fill"/>
    </svg>
    <div>
      There is no categories yet. You can create one <%= link_to 'here', new_category_path %>.
    </div>
  </div>
<% end %>
<br>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/home/index.html.erb
<main>
  <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
    <h1 class="display-4 fw-normal">Transaction Tracker</h1>
    <p class="fs-5 text-muted">Track your spending easily with Transaction Tracker.</p>
  </div>

  <div class="container px-4 py-3" id="features">
    <h2 class="pb-2 border-bottom">Features</h2>
    <div class="row g-2 py-4 row-cols-1 row-cols-lg-3">
      <div class="feature col">
        <h2>Easy to use</h2>
        <p>You can easily track your monthly spending for each categories</p>
      </div>
      <div class="feature col">
        <h2>Customizable</h2>
        <p>You can create your own categories to tailor your spending data to you!</p>
      </div>
      <div class="feature col">
        <h2>Free!</h2>
        <p>The tracker is totally free with no ads! We don't track you either, we only keep the essential information (Your email as well as your own categories and transactions) but you can delete everything at any point</p>
      </div>
    </div>
  </div>

  <div class="container px-4 py-3" id="Support">
    <h2 class="pb-2 border-bottom pt-2">Support</h2>
    <div class="col">
      <h3>If you have any questions, don't hesitate to reach out !</h3>
      <p>You can contact us at: transationtracker[@]afetiveau[dot]com</p>
    </div>
  </div>

</main>

app/views/layouts/_header.html.erb
<header>
  <div class="d-flex flex-column flex-md-row align-items-center pb-3 mb-4 border-bottom">
    <a href="/" class="d-flex align-items-center text-dark text-decoration-none">
      <span class="fs-4">Transaction Tracker</span>
    </a>

    <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
      <% if user_signed_in? %>
        <%= link_to "My Transactions", transactions_path, class: "me-3 py-2 text-dark text-decoration-none" %>
        <%= link_to "My Account", edit_user_registration_path, class: "me-3 py-2 text-dark text-decoration-none" %>
        <%= link_to "Sign Out", destroy_user_session_path, class: "me-3 py-2 text-dark text-decoration-none"  %>
    <% else %>
        <%= link_to "Sign Up", new_user_registration_path, class: "me-3 py-2 text-dark text-decoration-none" %>
        <%= link_to "Sign In", new_user_session_path, class: "me-3 py-2 text-dark text-decoration-none" %>
      <% end %>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Transaction</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script defer src="https://unpkg.com/alpinejs@3.x.x/dist/cdn.min.js"></script>
  </head>

  <body>
  <div class="container py-3">
    <%= render "layouts/header" %>
    <% if notice %>
      <p class="alert alert-success alert-dismissible fade show">
        <%= notice %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger alert-dismissible fade show">
        <%= alert %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </p>
    <% end %>
    <%= yield %>
  </div>
  </body>
</html>

app/views/transactions/_form.html.erb
<%= form_with(model: transaction) do |f| %>
  <% if transaction.errors.any? %>
    <div class="alert alert-danger" id="error_explanation">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
        <% transaction.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= f.label :name, "Transaction Name", { class: "form-label"} %>
    <%= f.text_field :name, { class: "form-control", placeholder: "Food", required: true } %>
  </div>

  <div class="mb-3">
    <%= f.label :transaction_date, "Transaction Date", { class: "form-label"} %>
    <%= f.date_field :transaction_date, { class: "form-control", required: true } %>
  </div>

  <div class="mb-3">
    <div class="row" x-data="currencyData()" x-init="
    inputPrice = <%= transaction.present? && transaction.price.present? ? transaction.price : 0.00 %>;
    convertedPrice = <%= transaction.present? && transaction.price.present? ? transaction.price : 0.00 %>;">
      <div class="col-md-6">
        <%= f.label :price, "Price", { class: "form-label"} %>
        <div class="input-group">
          <div class="input-group-text">$</div>
          <input type="number" class="form-control" placeholder="19.84" step=".01" x-model="inputPrice" @change.debounce="changeCurrency" required>
          <select class="form-select" x-model="currency" @change.debounce="changeCurrency">
            <option value="CAD" selected>CAD</option>
            <option value="USD">USD</option>
            <option value="EUR">EUR</option>
            <option value="AUD">AUD</option>
            <option value="AUD">JPY</option>
            <option value="AUD">NOK</option>
            <option value="AUD">GBP</option>
          </select>
        </div>
      </div>
      <div class="col-md-6">
        <%= f.label :price, "CAD Price", { class: "form-label"} %>
        <div class="input-group">
          <div class="input-group-text">$</div>
          <input type="number" name="transaction[price]" class="form-control" placeholder="19.84" step=".01" x-model="convertedPrice" required>
        </div>
      </div>
    </div>
  </div>

  <div class="mb-3">
    <%= f.label :category_id, "Category Name", { class: "form-label"} %>
    <%= f.select :category_id, @user.categories.pluck(:name, :id), {}, { class: "form-select"} %>
  </div>

  <%= f.hidden_field :user_id, value: @user.id %>

  <div class="actions">
    <%= f.submit "Submit", class: 'btn btn-primary' %>
  </div>
<% end %>

<script type="text/javascript" charset="utf-8">
    currencyData = () => {
        return {
            inputPrice: 0.00,
            currency: 'CAD',
            convertedPrice: 0.00,

            changeCurrency: async function() {
                if (this.currency === 'CAD') {
                    this.convertedPrice = Number.parseFloat(this.inputPrice).toFixed(2);
                } else {
                    await fetch(`https://freecurrencyapi.net/api/v2/latest?apikey=e65d3140-6968-11ec-9481-f9819ded001b&base_currency=${this.currency}`)
                        .then(response => response.json())
                        .then(data => {
                            this.convertedPrice = (data.data['CAD'] * this.inputPrice).toFixed(2);
                        })
                        .catch(error => {
                            console.error(error);
                        });
                }
            },
        }
    }
</script>

app/views/transactions/_transactions_table.html.erb
<div class="row">
  <% %w[January February March April May June July August September October November December].each do |month| %>
    <div class="col-md-3 mb-3">
        <div class="card scroll">
            <div class="card-header">
              <h5><%= month %> <%= @year %></h5>
              <button type="button" class="w-auto btn btn-primary btn-sm" data-bs-toggle="modal" data-bs-target="#modal-<%= month %>">See Transactions</button>
            </div>
            <div class="card-body ">
                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">Category</th>
                        <th scope="col">Price</th>
                    </tr>
                    </thead>
                    <tbody>
                    <% @categories.each do |category| %>
                    <tr>
                        <td><%= category.name %></td>
                        <td><%= number_to_currency(sum_of_category_for_month(category, month, @year)) %></td>
                    </tr>
                    <% end %>
                    <tr>
                        <td class="table-active">Total Expenses:</td>
                        <td class="table-active">-<%= number_to_currency(total_sum_for_month(month, @year, false)) %></td>
                    </tr>
                    <tr>
                      <td class="table-active">Total Income:</td>
                      <td class="table-active">+<%= number_to_currency(total_sum_for_month(month, @year, true)) %></td>
                    </tr>
                </table>
            </div>
        </div>
    </div>

    <div class="modal fade" id="modal-<%= month %>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-lg modal-dialog-scrollable">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel"><%= month %> <%= @year %> Transactions</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <% transactions = month_transactions(month, @year) %>
            <% if transactions.count > 0 %>
              <table class="table">
                <thead>
                <tr>
                  <th scope="col">#</th>
                  <th>Name</th>
                  <th>Price</th>
                  <th>Date</th>
                  <th>Edit</th>
                  <th>Delete</th>
                </tr>
                </thead>

                <tbody>
                <% transactions.each_with_index do |transaction, index| %>
                  <tr>
                    <th scope="row"><%= index %></th>
                    <td><%= transaction.name %></td>
                    <td><%= number_to_currency(transaction.price) %></td>
                    <td><%= transaction.transaction_date %></td>
                    <td><%= link_to 'Edit', edit_transaction_path(transaction), class: "btn btn-secondary" %></td>
                    <td><%= link_to 'Delete', transaction, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
                  </tr>
                <% end %>
                </tbody>
              </table>
            <% else %>
              <div class="alert alert-warning d-flex align-items-center" role="alert">
                <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Warning:">
                  <use xlink:href="#exclamation-triangle-fill"/>
                </svg>
                <div>
                  There is no transactions yet. You can create one <%= link_to 'here', new_transaction_path %>.
                </div>
              </div>
            <% end %>
            <br>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary">Save changes</button>
          </div>
        </div>
      </div>
    </div>
    <% end %>

    <div class="col-md-3 mb-3">
        <div class="card scroll">
            <h5 class="card-header">Full Year <%= @year %></h5>
            <div class="card-body ">
                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">Category</th>
                        <th scope="col">Price</th>
                    </tr>
                    </thead>
                    <tbody>
                    <% @categories.each do |category| %>
                    <tr>
                        <td><%= category.name %></td>
                        <td><%= number_to_currency(sum_of_category_for_year(category, @year)) %></td>
                    </tr>
                    <% end %>
                    <tr>
                        <td class="table-active">Total Expenses:</td>
                        <td class="table-active">-<%= number_to_currency(total_sum_for_year(@year, false)) %></td>
                    </tr>
                    <tr>
                      <td class="table-active">Total Income:</td>
                      <td class="table-active">+<%= number_to_currency(total_sum_for_year(@year, true)) %></td>
                    </tr>
                    <tr>
                      <td class="table-active">Total:</td>
                      <td class="table-active"><%= number_to_currency(total_sum_for_year(@year, true) - total_sum_for_year(@year, false)) %></td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
</div>

app/views/transactions/edit.html.erb
<h1>Editing Transaction</h1>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/index.html.erb
<h1>Transactions</h1>
<div class="d-flex justify-content-between">
  <div>
    <%= link_to 'Add Transaction', new_transaction_path, class: 'btn btn-outline-primary' %>
    <%= link_to 'Go to Category', categories_path, class: 'btn btn-outline-primary' %>
  </div>
  <div>
    <%= form_tag(transactions_path(format: "js"), class: "row row-cols-lg-auto g-1 align-items-center", remote: true, method: :get) do %>
      <div class="col-12">
        <%= select_tag :year, options_for_select(year_select), { class: "form-select" } %>
      </div>
      <div class="col-12">
        <%= submit_tag "Go", class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

<br><br>

<div id="transaction_table">
  <%= render(partial: "transactions/transactions_table") %>
</div>

app/views/transactions/index.js.erb
document.getElementById("transaction_table").innerHTML = ("<%= j render(partial: 'transactions/transactions_table') %>");

app/views/transactions/new.html.erb
<h1>New Transaction</h1>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Back', transactions_path %>